// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JournalEntry.Data.Models;

[Table("JournalHeader")]
public partial class JournalHeader
{
    [Key]
    public Guid JournalID { get; set; }

    public int EntryNo { get; set; }

    [Required]
    [StringLength(50)]
    public string SystemNo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EntryDate { get; set; }

    [Required]
    [StringLength(100)]
    public string TransactionType { get; set; }

    [StringLength(50)]
    public string DocumentNo { get; set; }

    [StringLength(100)]
    public string ShortName { get; set; }

    [Required]
    [StringLength(500)]
    public string Description { get; set; }

    [StringLength(500)]
    public string FilePath { get; set; }

    public long User_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Creation_Date { get; set; }

    public bool? Status { get; set; }

    [InverseProperty("Journal")]
    public virtual ICollection<JournalDetail> JournalDetails { get; set; } = new List<JournalDetail>();

    [ForeignKey("User_ID")]
    [InverseProperty("JournalHeaders")]
    public virtual User User { get; set; }
}