// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JournalEntry.Data.Models;

public partial class JournalDetail
{
    [Key]
    public Guid DetailID { get; set; }

    public Guid JournalID { get; set; }

    public Guid AccountID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string AccountNumber { get; set; }

    [StringLength(150)]
    public string AccountName { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Debit { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Credit { get; set; }

    [StringLength(500)]
    public string LineDescription { get; set; }

    [StringLength(500)]
    public string ReportDescription { get; set; }

    [ForeignKey("AccountID")]
    [InverseProperty("JournalDetails")]
    public virtual AccountsChart Account { get; set; }

    [ForeignKey("JournalID")]
    [InverseProperty("JournalDetails")]
    public virtual JournalHeader Journal { get; set; }
}