// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JournalEntry.Data.Models;
[Table("Users")]
public partial class User
{
    [Key]
    public long User_ID { get; set; }

    [Required]
    [StringLength(100)]
    public string UserName { get; set; }

    [StringLength(200)]
    public string Email { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<JournalHeader> JournalHeaders { get; set; } = new List<JournalHeader>();
}